name: "pnpm Install"
description: "Install pnpm for a particular folder in a workspace and use a cache. Intended to be run in a Node Docker container."
inputs:
  package-name: # @lux/sass, next, etc
    description: "This is the package in our workspace that we want to install."
    required: true
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4.0.0
      name: Install pnpm
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: sh
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-2-${{ inputs.package-name}}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-2

    - name: Install dependencies
      shell: sh
      run: |
        pnpm install --filter ${{ inputs.package-name }}
