name: Glow Client

on:
  pull_request:
    paths:
      - "packages/glow-client/**"

jobs:
  js_tests:
    name: JS Tests
    runs-on: ubuntu-24.04
    container: node:20.18.0-alpine3.19

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install PNPM and dependencies
        run: npm i pnpm@9.12.1 -g && pnpm install --filter @glow-xyz/solana-client... --frozen-lockfile
      - name: Install PNPM and dependencies
        run: npm i pnpm@9.12.1 -g && pnpm install --filter @glow-xyz/gloe-client... --frozen-lockfile
      - name: Build
        run: pnpm --filter @glow-xyz/solana-client run build
      - name: Lint
        run: pnpm --filter @glow-xyz/glow-client run lint
      - name: TSC
        run: pnpm --filter @glow-xyz/glow-client run tsc
      - name: Test
        run: pnpm --filter @glow-xyz/glow-client run test
